version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_PORT=8000
      - UPLOAD_DIR=uploads
      - TOP_K_WORDS=50
      - APP_VERSION=1.0.0
    volumes:
      - .:/app
