version: "3.9"
services:
  app:
    build: .
    ports:
      - "7500:7500"
    environment:
      - APP_PORT=7500
      - UPLOAD_DIR=uploads
      - TOP_K_WORDS=50
      - APP_VERSION=3.0.0
    volumes:
      - .:/app
    command: sh -c "uvicorn app:app --host 0.0.0.0 --port ${APP_PORT}"
